### ISSUE TITLE
Simulation

### ISSUE THREAD

**Issue by threetwoone-w** [pjhae/Mujoco_drone_landing#1]
Hello, I would like to know how to modify the code that can generate random car trajectory? Thank you!

**Comment by pjhae** [comment]
Hi, you can modify qvel to generate random trajectory!
**qvel = np.array([action[0], action[1], action[2], 0, action[3], 0, 0, 0, 0, 0, 0.28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])**
Thanks :)
