### ISSUE TITLE
How to register Drone-v1 env?

### ISSUE THREAD

**Issue by ZikenHuang** [pjhae/Mujoco_drone_landing#2]
Hello, when I use `register(
    id='Drone-v1',
    entry_point='gym.envs.Mujoco_autonomous_drone_landing.mujoco.drone_v1:DroneEnv',
)` to register Drone-v1 env, it comes up with the error `TypeError: __init__() missing 1 required positional argument: 'observation_space' was raised from the environment creator for Drone-v1 with kwargs ({})`, could you tell me how to fix it ? Thank you very much!!!

**Comment by ZikenHuang** [comment]
I found that this issue is caused by the version mismatch. I managed to solve this issue by using the lower version of `mujoco_py==2.1.2.14` and `stable_baselines3==1.4.0`.

**Comment by pjhae** [comment]
Sorry for the late reply. Congratulations on resolving it well. I wish you good luck in your research :)

**Comment by theoutca** [comment]
I'm interested in your project on GitHub and would like to know what the specific environmental dependencies are. Could you please provide details about the software, libraries, versions, and any other necessary components that the project relies on to run properly? This information will be extremely helpful for me to set up the environment and get the project up and running. Thank you!
